name: Shadowsocks Client Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Docker check
      run: docker version

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/mohsenmottaghi/cloak-shadowsocks-docker/shadowsocks-client:latest

    - name: Push Docker image
      run: |
        docker login docker.pkg.github.com --username mohsenmottaghi -p ${{ secrets.GITHUB_PACKAGES }}
        docker push docker.pkg.github.com/mohsenmottaghi/cloak-shadowsocks-docker/shadowsocks-client:latest

